# Generated by Django 5.0.1 on 2024-02-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_member', models.CharField(max_length=200)),
                ('members_compared', models.CharField(max_length=200)),
                ('similarity', models.FloatField(default=0.0)),
            ],
        ),
    ]
